Jan-31 16:43:14.415 [main] DEBUG nextflow.cli.Launcher - $> nextflow run gtf_insert.nf
Jan-31 16:43:14.527 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.3
Jan-31 16:43:14.557 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/rgrindle/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.4
Jan-31 16:43:14.572 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jan-31 16:43:14.574 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jan-31 16:43:14.578 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jan-31 16:43:14.593 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jan-31 16:43:14.700 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Jan-31 16:43:14.725 [main] INFO  nextflow.cli.CmdRun - Launching `gtf_insert.nf` [adoring_mayer] DSL2 - revision: d7ed52ee08
Jan-31 16:43:14.726 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jan-31 16:43:14.726 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jan-31 16:43:14.738 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/rgrindle/.nextflow/secrets/store.json
Jan-31 16:43:14.747 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@648ee871] - activable => nextflow.secret.LocalSecretsProvider@648ee871
Jan-31 16:43:14.832 [main] DEBUG nextflow.Session - Session UUID: 4e741946-6330-4f30-b462-18384fbcfc27
Jan-31 16:43:14.832 [main] DEBUG nextflow.Session - Run name: adoring_mayer
Jan-31 16:43:14.835 [main] DEBUG nextflow.Session - Executor pool size: 16
Jan-31 16:43:14.849 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=48; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jan-31 16:43:14.891 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.04.3 build 5875
  Created: 11-08-2023 18:37 UTC (14:37 EDT)
  System: Linux 4.18.0-372.9.1.el8.x86_64
  Runtime: Groovy 3.0.16 on Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190
  Encoding: UTF-8 (UTF-8)
  Process: 4169013@random.mdibl.net [209.222.195.242]
  CPUs: 16 - Mem: 141.4 GB (64.7 GB) - Swap: 32 MB (0)
Jan-31 16:43:14.933 [main] DEBUG nextflow.Session - Work-dir: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work [nfs]
Jan-31 16:43:14.934 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/bin
Jan-31 16:43:14.949 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jan-31 16:43:14.967 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jan-31 16:43:15.003 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jan-31 16:43:15.018 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Jan-31 16:43:15.139 [main] DEBUG nextflow.Session - Session start
Jan-31 16:43:16.334 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jan-31 16:43:16.523 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jan-31 16:43:16.524 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jan-31 16:43:16.533 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Jan-31 16:43:16.539 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=16; memory=141.4 GB; capacity=16; pollInterval=100ms; dumpInterval=5m
Jan-31 16:43:16.722 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: GTF_INSERT
Jan-31 16:43:16.723 [main] DEBUG nextflow.Session - Igniting dataflow network (4)
Jan-31 16:43:16.734 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > GTF_INSERT
Jan-31 16:43:16.735 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Jan-31 16:43:16.736 [main] DEBUG nextflow.Session - Session await
Jan-31 16:43:16.956 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jan-31 16:43:16.959 [Task submitter] INFO  nextflow.Session - [0f/b8b63a] Submitted process > GTF_INSERT (1)
Jan-31 16:43:17.056 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: GTF_INSERT (1); status: COMPLETED; exit: 127; error: -; workDir: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/0f/b8b63a913e15f7fe3a8ef385211c8a]
Jan-31 16:43:17.062 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=GTF_INSERT (1); work-dir=/compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/0f/b8b63a913e15f7fe3a8ef385211c8a
  error [nextflow.exception.ProcessFailedException]: Process `GTF_INSERT (1)` terminated with an error exit status (127)
Jan-31 16:43:17.076 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'GTF_INSERT (1)'

Caused by:
  Process `GTF_INSERT (1)` terminated with an error exit status (127)

Command executed:

  find_overlaps.py all_double.combined.gtf
  parse_gtf_to_dict_cmp_ref.py find_overlaps.gtf
  extract_key_value.py all_double.tracking
  check_unique_keys.py key_value_genes.json
  update_keys.py key_value_genes.json gtf_to_dict_gffcmp.json
  parse_gtf_2_dict_geneid.py Danio_rerio.GRCz11.110.gtf
  insert_by_start.py updated_gffcmp.json parse_reference_gtf.json
  json_2_gtf.py overlap_inserted.json
  find_novel_tscripts.py all_double.combined.gtf overlap_inserted.gtf

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: find_overlaps.py: command not found

Work dir:
  /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/0f/b8b63a913e15f7fe3a8ef385211c8a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Jan-31 16:43:17.084 [main] DEBUG nextflow.Session - Session await > all processes finished
Jan-31 16:43:17.087 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `GTF_INSERT (1)` terminated with an error exit status (127)
Jan-31 16:43:17.107 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jan-31 16:43:17.115 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=23ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Jan-31 16:43:17.296 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jan-31 16:43:17.313 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
