Jan-31 16:41:00.068 [main] DEBUG nextflow.cli.Launcher - $> nextflow run gtf_insert.nf
Jan-31 16:41:00.155 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.3
Jan-31 16:41:00.179 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/rgrindle/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.4
Jan-31 16:41:00.194 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jan-31 16:41:00.195 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jan-31 16:41:00.199 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jan-31 16:41:00.213 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jan-31 16:41:00.312 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Jan-31 16:41:00.337 [main] INFO  nextflow.cli.CmdRun - Launching `gtf_insert.nf` [confident_lamarck] DSL2 - revision: 2bc6e456b3
Jan-31 16:41:00.338 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jan-31 16:41:00.338 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jan-31 16:41:00.352 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/rgrindle/.nextflow/secrets/store.json
Jan-31 16:41:00.362 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@30feffc] - activable => nextflow.secret.LocalSecretsProvider@30feffc
Jan-31 16:41:00.449 [main] DEBUG nextflow.Session - Session UUID: 9e93dc73-a282-4695-9a19-4dc52095ba8a
Jan-31 16:41:00.449 [main] DEBUG nextflow.Session - Run name: confident_lamarck
Jan-31 16:41:00.452 [main] DEBUG nextflow.Session - Executor pool size: 16
Jan-31 16:41:00.467 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=48; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jan-31 16:41:00.507 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.04.3 build 5875
  Created: 11-08-2023 18:37 UTC (14:37 EDT)
  System: Linux 4.18.0-372.9.1.el8.x86_64
  Runtime: Groovy 3.0.16 on Java HotSpot(TM) 64-Bit Server VM 17.0.6+9-LTS-190
  Encoding: UTF-8 (UTF-8)
  Process: 4168510@random.mdibl.net [209.222.195.242]
  CPUs: 16 - Mem: 141.4 GB (64.7 GB) - Swap: 32 MB (0)
Jan-31 16:41:00.542 [main] DEBUG nextflow.Session - Work-dir: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work [nfs]
Jan-31 16:41:00.542 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/bin
Jan-31 16:41:00.555 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jan-31 16:41:00.569 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jan-31 16:41:00.599 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jan-31 16:41:00.612 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 17; maxThreads: 1000
Jan-31 16:41:00.708 [main] DEBUG nextflow.Session - Session start
Jan-31 16:41:01.938 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jan-31 16:41:02.130 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Jan-31 16:41:02.130 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Jan-31 16:41:02.140 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Jan-31 16:41:02.147 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=16; memory=141.4 GB; capacity=16; pollInterval=100ms; dumpInterval=5m
Jan-31 16:41:02.309 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: GTF_INSERT
Jan-31 16:41:02.309 [main] DEBUG nextflow.Session - Igniting dataflow network (4)
Jan-31 16:41:02.318 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > GTF_INSERT
Jan-31 16:41:02.319 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Jan-31 16:41:02.319 [main] DEBUG nextflow.Session - Session await
Jan-31 16:41:02.524 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jan-31 16:41:02.528 [Task submitter] INFO  nextflow.Session - [ca/54484e] Submitted process > GTF_INSERT (1)
Jan-31 16:41:02.619 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: GTF_INSERT (1); status: COMPLETED; exit: 127; error: -; workDir: /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/ca/54484e3eabae9c7ba32fa0e585d68c]
Jan-31 16:41:02.624 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=GTF_INSERT (1); work-dir=/compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/ca/54484e3eabae9c7ba32fa0e585d68c
  error [nextflow.exception.ProcessFailedException]: Process `GTF_INSERT (1)` terminated with an error exit status (127)
Jan-31 16:41:02.637 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'GTF_INSERT (1)'

Caused by:
  Process `GTF_INSERT (1)` terminated with an error exit status (127)

Command executed:

  find_overlaps.py all_double.combined.gtf
  parse_gtf_to_dict_cmp_ref.py find_overlaps.gtf
  extract_key_value.py all_double.tracking
  check_unique_keys.py key_value_genes.json
  update_keys.py key_value_genes.json gtf_to_dict_gffcmp.json
  parse_gtf_2_dict_geneid.py Danio_rerio.GRCz11.110.gtf
  insert_by_start.py updated_gffcmp.json parse_reference_gtf.json
  json_2_gtf.py overlap_inserted.json
  find_novel_tscripts.py all_double.combined.gtf overlap_inserted.gtf

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: find_overlaps.py: command not found

Work dir:
  /compbio/scratch/rgrindle/transcriptome_pipeline/rnaseq_transcriptome_update/modules/local/work/ca/54484e3eabae9c7ba32fa0e585d68c

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Jan-31 16:41:02.645 [main] DEBUG nextflow.Session - Session await > all processes finished
Jan-31 16:41:02.647 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `GTF_INSERT (1)` terminated with an error exit status (127)
Jan-31 16:41:02.662 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jan-31 16:41:02.670 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=49ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Jan-31 16:41:02.858 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jan-31 16:41:02.874 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
